"""add call table

Revision ID: 411241d6277b
Revises:
Create Date: 2022-01-30 21:05:37.635953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "411241d6277b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "call",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("sid", sa.Text(), nullable=True),
        sa.Column("scheduled_to", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("WAITING", "REQUESTED", "COMPLETED", "FAILED", name="callstatus"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("call")
    # ### end Alembic commands ###
